### YamlMime:ManagedReference
items:
- uid: Utils.Configs.JsonConfigLoader`1
  commentId: T:Utils.Configs.JsonConfigLoader`1
  id: JsonConfigLoader`1
  parent: Utils.Configs
  children:
  - Utils.Configs.JsonConfigLoader`1.#ctor(System.String,Microsoft.Extensions.Logging.ILogger)
  - Utils.Configs.JsonConfigLoader`1.LoadConfig
  langs:
  - csharp
  - vb
  name: JsonConfigLoader<T>
  nameWithType: JsonConfigLoader<T>
  fullName: Utils.Configs.JsonConfigLoader<T>
  type: Class
  source:
    remote:
      path: PingPongSchema/Configs/JsonConfigLoader.cs
      branch: Client_ConnectionPool
      repo: https://github.com/iLakis/PingPongConsoleApp.git
    id: JsonConfigLoader
    path: PingPongSchema/Configs/JsonConfigLoader.cs
    startLine: 5
  assemblies:
  - Utils
  namespace: Utils.Configs
  syntax:
    content: 'public class JsonConfigLoader<T> : IConfigLoader<T> where T : class, new()'
    typeParameters:
    - id: T
    content.vb: Public Class JsonConfigLoader(Of T As {Class, New}) Implements IConfigLoader(Of T)
  inheritance:
  - System.Object
  implements:
  - Utils.Configs.IConfigLoader{{T}}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  nameWithType.vb: JsonConfigLoader(Of T)
  fullName.vb: Utils.Configs.JsonConfigLoader(Of T)
  name.vb: JsonConfigLoader(Of T)
- uid: Utils.Configs.JsonConfigLoader`1.#ctor(System.String,Microsoft.Extensions.Logging.ILogger)
  commentId: M:Utils.Configs.JsonConfigLoader`1.#ctor(System.String,Microsoft.Extensions.Logging.ILogger)
  id: '#ctor(System.String,Microsoft.Extensions.Logging.ILogger)'
  parent: Utils.Configs.JsonConfigLoader`1
  langs:
  - csharp
  - vb
  name: JsonConfigLoader(string, ILogger)
  nameWithType: JsonConfigLoader<T>.JsonConfigLoader(string, ILogger)
  fullName: Utils.Configs.JsonConfigLoader<T>.JsonConfigLoader(string, Microsoft.Extensions.Logging.ILogger)
  type: Constructor
  source:
    remote:
      path: PingPongSchema/Configs/JsonConfigLoader.cs
      branch: Client_ConnectionPool
      repo: https://github.com/iLakis/PingPongConsoleApp.git
    id: .ctor
    path: PingPongSchema/Configs/JsonConfigLoader.cs
    startLine: 10
  assemblies:
  - Utils
  namespace: Utils.Configs
  syntax:
    content: public JsonConfigLoader(string configFilePath, ILogger logger)
    parameters:
    - id: configFilePath
      type: System.String
    - id: logger
      type: Microsoft.Extensions.Logging.ILogger
    content.vb: Public Sub New(configFilePath As String, logger As ILogger)
  overload: Utils.Configs.JsonConfigLoader`1.#ctor*
  nameWithType.vb: JsonConfigLoader(Of T).New(String, ILogger)
  fullName.vb: Utils.Configs.JsonConfigLoader(Of T).New(String, Microsoft.Extensions.Logging.ILogger)
  name.vb: New(String, ILogger)
- uid: Utils.Configs.JsonConfigLoader`1.LoadConfig
  commentId: M:Utils.Configs.JsonConfigLoader`1.LoadConfig
  id: LoadConfig
  parent: Utils.Configs.JsonConfigLoader`1
  langs:
  - csharp
  - vb
  name: LoadConfig()
  nameWithType: JsonConfigLoader<T>.LoadConfig()
  fullName: Utils.Configs.JsonConfigLoader<T>.LoadConfig()
  type: Method
  source:
    remote:
      path: PingPongSchema/Configs/JsonConfigLoader.cs
      branch: Client_ConnectionPool
      repo: https://github.com/iLakis/PingPongConsoleApp.git
    id: LoadConfig
    path: PingPongSchema/Configs/JsonConfigLoader.cs
    startLine: 15
  assemblies:
  - Utils
  namespace: Utils.Configs
  example: []
  syntax:
    content: public T LoadConfig()
    return:
      type: '{T}'
    content.vb: Public Function LoadConfig() As T
  overload: Utils.Configs.JsonConfigLoader`1.LoadConfig*
  implements:
  - Utils.Configs.IConfigLoader{{T}}.LoadConfig
  nameWithType.vb: JsonConfigLoader(Of T).LoadConfig()
  fullName.vb: Utils.Configs.JsonConfigLoader(Of T).LoadConfig()
references:
- uid: Utils.Configs
  commentId: N:Utils.Configs
  href: Utils.html
  name: Utils.Configs
  nameWithType: Utils.Configs
  fullName: Utils.Configs
  spec.csharp:
  - uid: Utils
    name: Utils
    href: Utils.html
  - name: .
  - uid: Utils.Configs
    name: Configs
    href: Utils.Configs.html
  spec.vb:
  - uid: Utils
    name: Utils
    href: Utils.html
  - name: .
  - uid: Utils.Configs
    name: Configs
    href: Utils.Configs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Utils.Configs.IConfigLoader{{T}}
  commentId: T:Utils.Configs.IConfigLoader{`0}
  parent: Utils.Configs
  definition: Utils.Configs.IConfigLoader`1
  href: Utils.Configs.IConfigLoader-1.html
  name: IConfigLoader<T>
  nameWithType: IConfigLoader<T>
  fullName: Utils.Configs.IConfigLoader<T>
  nameWithType.vb: IConfigLoader(Of T)
  fullName.vb: Utils.Configs.IConfigLoader(Of T)
  name.vb: IConfigLoader(Of T)
  spec.csharp:
  - uid: Utils.Configs.IConfigLoader`1
    name: IConfigLoader
    href: Utils.Configs.IConfigLoader-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Utils.Configs.IConfigLoader`1
    name: IConfigLoader
    href: Utils.Configs.IConfigLoader-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Utils.Configs.IConfigLoader`1
  commentId: T:Utils.Configs.IConfigLoader`1
  href: Utils.Configs.IConfigLoader-1.html
  name: IConfigLoader<T>
  nameWithType: IConfigLoader<T>
  fullName: Utils.Configs.IConfigLoader<T>
  nameWithType.vb: IConfigLoader(Of T)
  fullName.vb: Utils.Configs.IConfigLoader(Of T)
  name.vb: IConfigLoader(Of T)
  spec.csharp:
  - uid: Utils.Configs.IConfigLoader`1
    name: IConfigLoader
    href: Utils.Configs.IConfigLoader-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Utils.Configs.IConfigLoader`1
    name: IConfigLoader
    href: Utils.Configs.IConfigLoader-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Utils.Configs.JsonConfigLoader`1.#ctor*
  commentId: Overload:Utils.Configs.JsonConfigLoader`1.#ctor
  href: Utils.Configs.JsonConfigLoader-1.html#Utils_Configs_JsonConfigLoader_1__ctor_System_String_Microsoft_Extensions_Logging_ILogger_
  name: JsonConfigLoader
  nameWithType: JsonConfigLoader<T>.JsonConfigLoader
  fullName: Utils.Configs.JsonConfigLoader<T>.JsonConfigLoader
  nameWithType.vb: JsonConfigLoader(Of T).New
  fullName.vb: Utils.Configs.JsonConfigLoader(Of T).New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Microsoft.Extensions.Logging.ILogger
  commentId: T:Microsoft.Extensions.Logging.ILogger
  parent: Microsoft.Extensions.Logging
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger
  name: ILogger
  nameWithType: ILogger
  fullName: Microsoft.Extensions.Logging.ILogger
- uid: Microsoft.Extensions.Logging
  commentId: N:Microsoft.Extensions.Logging
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.Logging
  nameWithType: Microsoft.Extensions.Logging
  fullName: Microsoft.Extensions.Logging
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging
- uid: Utils.Configs.JsonConfigLoader`1.LoadConfig*
  commentId: Overload:Utils.Configs.JsonConfigLoader`1.LoadConfig
  href: Utils.Configs.JsonConfigLoader-1.html#Utils_Configs_JsonConfigLoader_1_LoadConfig
  name: LoadConfig
  nameWithType: JsonConfigLoader<T>.LoadConfig
  fullName: Utils.Configs.JsonConfigLoader<T>.LoadConfig
  nameWithType.vb: JsonConfigLoader(Of T).LoadConfig
  fullName.vb: Utils.Configs.JsonConfigLoader(Of T).LoadConfig
- uid: Utils.Configs.IConfigLoader{{T}}.LoadConfig
  commentId: M:Utils.Configs.IConfigLoader{`0}.LoadConfig
  parent: Utils.Configs.IConfigLoader{{T}}
  definition: Utils.Configs.IConfigLoader`1.LoadConfig
  href: Utils.Configs.IConfigLoader-1.html#Utils_Configs_IConfigLoader_1_LoadConfig
  name: LoadConfig()
  nameWithType: IConfigLoader<T>.LoadConfig()
  fullName: Utils.Configs.IConfigLoader<T>.LoadConfig()
  nameWithType.vb: IConfigLoader(Of T).LoadConfig()
  fullName.vb: Utils.Configs.IConfigLoader(Of T).LoadConfig()
  spec.csharp:
  - uid: Utils.Configs.IConfigLoader{`0}.LoadConfig
    name: LoadConfig
    href: Utils.Configs.IConfigLoader-1.html#Utils_Configs_IConfigLoader_1_LoadConfig
  - name: (
  - name: )
  spec.vb:
  - uid: Utils.Configs.IConfigLoader{`0}.LoadConfig
    name: LoadConfig
    href: Utils.Configs.IConfigLoader-1.html#Utils_Configs_IConfigLoader_1_LoadConfig
  - name: (
  - name: )
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: Utils.Configs.IConfigLoader`1.LoadConfig
  commentId: M:Utils.Configs.IConfigLoader`1.LoadConfig
  href: Utils.Configs.IConfigLoader-1.html#Utils_Configs_IConfigLoader_1_LoadConfig
  name: LoadConfig()
  nameWithType: IConfigLoader<T>.LoadConfig()
  fullName: Utils.Configs.IConfigLoader<T>.LoadConfig()
  nameWithType.vb: IConfigLoader(Of T).LoadConfig()
  fullName.vb: Utils.Configs.IConfigLoader(Of T).LoadConfig()
  spec.csharp:
  - uid: Utils.Configs.IConfigLoader`1.LoadConfig
    name: LoadConfig
    href: Utils.Configs.IConfigLoader-1.html#Utils_Configs_IConfigLoader_1_LoadConfig
  - name: (
  - name: )
  spec.vb:
  - uid: Utils.Configs.IConfigLoader`1.LoadConfig
    name: LoadConfig
    href: Utils.Configs.IConfigLoader-1.html#Utils_Configs_IConfigLoader_1_LoadConfig
  - name: (
  - name: )
- uid: T
  name: T
  nameWithType: T
  fullName: T
